blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/runkids/PackageFlow#readme
    about: Check out the README for usage information
  - name: Discussions
    url: https://github.com/runkids/PackageFlow/discussions
    about: Ask questions and share ideas in Discussions
